# Generated by Django 2.2.4 on 2019-08-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('meal_type', models.CharField(max_length=20)),
                ('meal_date', models.DateField()),
                ('calories', models.CharField(max_length=6)),
                ('protein', models.CharField(max_length=6)),
                ('fat', models.CharField(max_length=6)),
                ('carbs', models.CharField(max_length=6)),
            ],
        ),
    ]
